SELECT TLP_TERMINE.Terminnummer, TLP_TERMINE.Datum, TLP_TERMINE.Bezeichnung, TLP_TERMINE.Mitgliedsnr, TLP_TERMINE.Raum, TLP_TERMINE.Straﬂe, TLP_TERMINE.PLZ, TLP_TERMINE.Ort, TLP_TERMINE.Beginn, TLP_TERMINE.Ende, TLP_TERMINE.Clubname_kurz
FROM TLP_TERMINE
ORDER BY TLP_TERMINE.Datum, TLP_TERMINE.Bezeichnung, TLP_TERMINE.Mitgliedsnr;

